name: flutter_feature_first_template
description: Flutter POC App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  flutter_web_plugins:
      sdk: flutter

  cupertino_icons: ^1.0.8
  # HTTP клиент
  dio: ^5.0.0
  
  flutter_riverpod: ^2.5.1

  # Generator and Annotations
  riverpod_annotation: ^2.3.5
  freezed_annotation: ^3.0.0
  # Адаптивный дизайн
  responsive_framework: ^0.2.0
  
  # # State Management (простейший)
  # provider: ^6.0.0
  
  # Индикатор загрузки
  shimmer: ^3.0.0
  
  # Кэширование изображений
  cached_network_image: ^3.2.0
  
  # Для удобной работы с JSON
  json_annotation: ^4.8.0

   # Для навигации с поддержкой web
  go_router: ^13.0.0  # Лучшая для web routing

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^6.0.0
  build_runner: ^2.0.0
  json_serializable: ^6.0.0
  riverpod_generator: any

flutter:
  uses-material-design: true

